Resolve all mypy no-untyped-def errors which require "-> None"
This is one step towards adding mypy and shipping type hints.
This change fixes all errors of the format:

```
tests/test_codeblock.py:136: error: Function is missing a return type annotation  [no-untyped-def]
tests/test_codeblock.py:136: note: Use "-> None" if function does not return a value
```

when running:

```
mypy --strict sybil tests
```