Avoid using py.path.local
If using `py.path.local`, we will have to skip errors regarding `py.path` for `mypy`.
I chose to propose this change instead, as `py.path.local` is not the modern solution - `pathlib.Path` is.

The `mypy` errors that this removes:

```
sybil/integration/pytest.py:15: error: Skipping analyzing "py.path": module is installed, but missing library stubs or py.typed marker  [import-untyped]
sybil/integration/pytest.py:15: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
sybil/integration/pytest.py:15: error: Skipping analyzing "py": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```

In `pytest` `7.0.0`, there were changes made which make this change possible.

See https://docs.pytest.org/en/7.1.x/changelog.html#id48.
That changelog includes:

```
```

and:

```

pytest_collect_file - The file_path parameter (equivalent to existing path parameter).
```