Define pytest skipif as variable not function
This resolves mypy errors in the format:

```
tests/test_document.py:13: error: Call to untyped function "skip_if_37_or_older" in typed context  [no-untyped-call]
```

We could instead add a type to the existing function but:

* `pytest` does not ship a public type for this, so this change would rely on importing a private type
* This change matches the documented way of sharing skipif markers in the pytest documentation at https://docs.pytest.org/en/7.1.x/how-to/skipping.html#id1